baseURL = "https://coherentnonsense.com/"
languageCode = "en-us"
title = "Coherent Nonsense"
publishDir = "docs"
[params]
  github = "https://github.com/coherentnonsense"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = -4
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = -3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = -1
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 0
